name: Shorthand
description: A starting point for Dart libraries or applications.
version: 0.0.11
#homepage: https://www.example.com
#author: Eric <email@example.com>

environment:
  sdk: '>=2.0.0'

dependencies:
  sqljocky5:
    git: https://github.com/dart-db/sqljocky5.git

  options_file:
    git: https://github.com/ferrerj/optionsfile.git
#  path: ^1.4.1
  pool:
    version: "^1.0.0"

dev_dependencies:

