name: Shorthand
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Eric <email@example.com>

environment:
  sdk: '>=1.20.1'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
